Project.WebOnline.MVC/Controllers/SaleOrderController.cs
using Newtonsoft.Json;
using Project.CheckOut.Models;
using Project.CheckOut.UnitOfWork;
using Project.CheckOut_MVC.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Project.WebOnline.Controllers
{
    public class SaleOrderController : Controller
    {
        protected readonly IUnitOfWork _unit;

        public SaleOrderController(IUnitOfWork unit)
        {
            _unit = unit;
        }

        // GET: Order
        public ActionResult Index()
        {
            var identity = (ClaimsIdentity)User.Identity;
            var userId = identity.Claims.FirstOrDefault(x => x.Type.ToLower().Contains("userdata")).Value;

            return View(_unit.Order.GetOrdersCustomized(int.Parse(userId)));
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Order/Create
        public ActionResult Create(string OrderNumber)
        {
            return View(new Order { OrderNumber = OrderNumber });
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(TotalCart detail)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction("Index");
                }

                var identity = (ClaimsIdentity)User.Identity;
                var userEmail = identity.Claims.FirstOrDefault(x => x.Type.ToLower().Contains("emailaddress")).Value;
                var authenticationClaim = identity.Claims.FirstOrDefault(x => x.Type.ToLower().Contains("authentication"));
                int userId = _unit.UserWeb.GetUserCustomized(userEmail);

                var response = _unit.Order.CreateCustomized(userId);
                if (response.Item2 == 0 && string.IsNullOrEmpty(response.Item1))
                    return RedirectToAction("Index");

                //var productList = JsonConvert.SerializeObject(new List<int> { productId, productId });
                var productsList = JsonConvert.SerializeObject(detail.Cart);
                var responseOrderDetail = _unit.OrderDetail.CreateCustomized(response.Item2, productsList, detail.TotalAmount);

                _unit.Cart.DeleteCartCustomized(userEmail);
                return RedirectToAction("Create", new { OrderNumber = response.Item1 });
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

        //OrderDetail
        public PartialViewResult OrderDetail(int OrderId, string OrderNumber)
        {
            var orderDetail = _unit.OrderDetail.GetOrderDetailCustomized(OrderId);
            var fields = JsonConvert.DeserializeObject<List<CartDetail>>(orderDetail.Products);

            var totalCart = new TotalCart
            {
                OrderNumber = OrderNumber,
                TotalAmount = orderDetail.TotalPay
            };

            totalCart.Cart = fields;

            return PartialView("_Index", totalCart);
        }
    }
}

Project.WebOnline.MVC/Controllers/SaleOrderDetailController.cs
using Newtonsoft.Json;
using Project.CheckOut.Models;
using Project.CheckOut.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.WebOnline.Controllers
{
    public class SaleOrderDetailController : Controller
    {
        protected readonly IUnitOfWork _unit;

        public SaleOrderDetailController(IUnitOfWork unit)
        {
            _unit = unit;
        }

        // GET: OrderDetail
        //public ActionResult Index(int OrderId, string OrderNumber)
        //{
        //    var orderDetail = _unit.OrderDetail.GetOrderDetailCustomized(OrderId);
        //    var fields = JsonConvert.DeserializeObject<List<CartDetail>>(orderDetail.Products);

        //    var totalCart = new TotalCart
        //    {
        //        OrderNumber = OrderNumber,
        //        TotalAmount = orderDetail.TotalPay
        //    };

        //    totalCart.Cart = fields;

        //    return View(totalCart);
        //}

        public PartialViewResult Index(int OrderId, string OrderNumber)
        {
            var orderDetail = _unit.OrderDetail.GetOrderDetailCustomized(OrderId);
            var fields = JsonConvert.DeserializeObject<List<CartDetail>>(orderDetail.Products);

            var totalCart = new TotalCart
            {
                OrderNumber = OrderNumber,
                TotalAmount = orderDetail.TotalPay
            };

            totalCart.Cart = fields;

            return PartialView("_Index", totalCart);
        }
    }
}

Project.WebOnline.MVC/Views/SaleOrder/Create.cshtml
@model Project.CheckOut.Models.Order

@{
	ViewBag.Title = "Order Page";
}
<div class="jumbotron">
	<div class="container">
		<div class="row bs-wizard" style="border-bottom:0;">
			<div class="container">

				<div class="stepwizard">
					<div class="stepwizard-row setup-panel">
						<div class="stepwizard-step paso">
							<a href="#VerifyEmail-step" type="button" class="btn btn-success btn-circle" id="VerifyEmail-step-1">
								<span class="fa fa-check"></span>
							</a>
							<p>Verificar productos</p>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<p class="text-center">
							<b class="text-center">Gracias por Comprar!!</b> Tu orden es: @Model.OrderNumber
						</p>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

Project.WebOnline.MVC/Views/SaleOrder/Index.cshtml
@model IEnumerable<Project.CheckOut.Models.Order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConfirmDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @if(item.ConfirmDate == null)
						{
								<text>-</text>
						}
						else
						{
							@Html.DisplayFor(modelItem => item.ConfirmDate)
						}

        </td>
				<td>
						@if (item.ShippedDate == null)
						{
								<text>-</text>
						}
						else
						{
							@Html.DisplayFor(modelItem => item.ShippedDate)
						}
				</td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
				<td>
					@*@using (Html.BeginForm("Index", "SaleOrderDetail", FormMethod.Get))
					{
							<input type="number" id="OrderID" name="OrderID" value="@item.OrderID" hidden />
							<input type="number" id="OrderNumber" name="OrderNumber" value="@item.OrderNumber" hidden />
							<input type="submit" value="Detalle" class="btn-link" />
					}*@
					
					@Modal.GetModal("Detalle de la Orden", "customer.closeModal();")
					{
					<a href="#" onclick="webonline.getModal('@Url.Action("OrderDetail", new { OrderID = item.OrderID, OrderNumber = item.OrderNumber })');
              return false;" data-toggle="modal" data-target="#modal-container"
              class="btn-link">
							Detalle
					</a>
					}
				</td>
    </tr>
}

</table>

<script src="~/App_JS/webonline.js"></script>

Project.WebOnline.MVC/Views/SaleOrder/_Index.cshtml
@model Project.CheckOut.Models.TotalCart


<h3>
	Número de Orden: @Model.OrderNumber
</h3>

<div class="form-horizontal">
	<table class="table">
		<tr>
			<th>
				Nombre del Producto
			</th>
			<th>
				Descuento
			</th>
			<th>
				Cantidad
			</th>
			<th>
				Precio por Unidad
			</th>
		</tr>

		@foreach (var item in Model.Cart)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.ProductName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Discount)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Quantity)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Price)
				</td>
			</tr>
		}
		<tr>
			<td></td>
			<td></td>
			<td>
				Total pagado:
			</td>
			<td>
				@Html.DisplayFor(model => model.TotalAmount)
			</td>
		</tr>
	</table>
	</div>